apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: n1t2or7dg-nodejs 
  janus-idp.io/tekton: n1t2or7dg-nodejs
  backstage.io/kubernetes-id: n1t2or7dg-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: n1t2or7dg-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml