apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: n1t2or7dg-nodejs-gitops
  description: This is GitOps manifest for n1t2or7dg-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=n1t2or7dg-nodejs
    backstage.io/kubernetes-id: n1t2or7dg-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: n1t2or7dg-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:n1t2or7dg-nodejs
