apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: n1t2or7dg-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: n1t2or7dg-nodejs 
  name: n1t2or7dg-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: n1t2or7dg-nodejs 
